title: "Mi Página Académica"
description: "Aquí encontraras información sobre mi carrera profesoral, investigativa y desarrollo institucional"
theme: jekyll-theme-cayman
url: "https://pozost.github.io"
baseurl: "/MyPersonalPage"
markdown: kramdown
kramdown:
  math_engine: mathjax
