title: "Dra. Alejandra Tabares Pozos"
description: "Página personal enfocada en investigación, docencia y publicaciones."
theme: minima
url: "https://pozost.github.io"
baseurl: "/MyPersonalPage"
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: pretty
paginate: 5